apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: github-token-exchange
  namespace: microservices
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.org/redirect-to-https: 'true'
spec:
  ingressClassName: nginx-ext
  rules:
    - host: token.kube.searchspring.io
      http:
        paths:
          - backend:
              service:
                name: github-token-exchange
                port:
                  number: 80
            path: /
            pathType: Prefix
