apiVersion: v1
kind: Service
metadata:
  labels:
    app: github-token-exchange
  name: github-token-exchange
  namespace: microservices
spec:
  ports:
    - name: service
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: github-token-exchange
  sessionAffinity: None
  type: ClusterIP
